### ISSUE TITLE
tt_embeddings_cuda.cu(1779): error: a value of type "void" cannot be used to initialize an entity of type "float"

### ISSUE THREAD

**Issue by Bruceuang** [facebookresearch/FBTT-Embedding#15]
hi, I get an error with `python setup.py install`:
`tt_embeddings_cuda.cu(1779): error: a value of type "void" cannot be used to initialize an entity of type "float"`;

**Comment by Bruceuang** [comment]
pytorch1.7 is work

**Comment by yangcug** [comment]
hi I have the same error 
I have tried python 3.8.5+ cudatoolkit 10.1.243+ torch 1.6.0; Python 3.8.5+  cudatoolkit 10.1.243+ torch 1.7.1
Could you tell me your environment?
